baseURL = "https://snh48-lore.pages.dev/"
languageCode = "en-us"
title = "SNH48 Hybrid Universe"
theme = "hugo-theme-stack"
defaultContentLanguage = "en"

[params]
mainSections = [ "posts" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006"

  [params.sidebar]
  compact = false
  subtitle = "Aiming to make sense of the stage lore, one post at a time"

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/logo.png"

  [params.article]
  headingAnchor = false
  toc = true
  readingTime = false

    [params.article.license]
    enabled = false

  [params.comments]
  enabled = false

  [[params.widgets.homepage]]
    type = "search"

  [[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.page]]
    type = "search"

  [[params.widgets.page]]
    type = "categories"
    [params.widgets.page.params]
      limit = 10

  [[params.widgets.page]]
    type = "tag-cloud"
    [params.widgets.page.params]
      limit = 10

[menu]
  [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/shushuwuwu"
	weight = 1
	[menu.social.params]
	  icon = "brand-twitter"
	  newTab = true

[taxonomies]
  tag = "tags"
  category = "categories"
  team = "teams"