baseURL = "https://snh48-lore.pages.dev/"
languageCode = "en-us"
title = "SNH48 Hybrid Universe"
theme = "hugo-theme-stack"
defaultContentLanguage = "en"

[params]
  subtitle = "Trying to make sense of the SNH48 Hybrid Universe lore"
  mainSections = ["posts"]
  featuredImageField = "cover"
  toc = true
  defaultTheme = "auto"

  [params.search]
    enable = true

  [params.sidebar]
    enable = true

[taxonomies]
  tag = "tags"
  category = "categories"
  team = "teams"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "teams"
    name = "Teams"
    url = "/teams/"
    weight = 3
